name: test1
description: iOS local music player (SoundCloud style)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  ffmpeg_kit_flutter_new_min_gpl: ^2.1.1

  # ðŸ”Š Audio
  just_audio: ^0.9.42
  audio_service: ^0.18.15
  audio_session: ^0.1.21

  # ðŸ“ File / Permission
  file_picker: ^8.1.7
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  path: ^1.9.0

  # ðŸ—œ ZIP (BACKUP)
  archive: ^3.4.10

  share_plus: ^10.0.2
  # ðŸ’¾ DB
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.2

  # UI
  flutter_slidable: ^3.1.1

  # Settings
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  android: true
  image_path: assets/icon/icon.png
  remove_alpha_ios: true
